# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'InstaCloneFirebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'  
pod 'FirebaseStorage' 

  # Pods for InstaCloneFirebase

  target 'InstaCloneFirebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InstaCloneFirebaseUITests' do
    # Pods for testing
  end

end
